# Generated by Django 3.2.9 on 2021-12-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='expedidaFactura',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Factura expedida por'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='expedidaPoliza',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Póliza expedida por'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='expedidaTarjeta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tarjeta expedida por'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='facturaVehiculo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Factura vehículo'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='fechaFactura',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha factura'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='fechaPoliza',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha vigencia póliza'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='fechaTarjeta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha tarjeta'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='polizaVehiculo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Póliza vehículo'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='tarjetaVehiculo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tarjeta vehículo'),
        ),
    ]
