# Generated by Django 3.2.9 on 2024-03-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0004_auto_20240228_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='clausula',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='domicilio_sociedad',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='empresa',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='fecha_constitucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='objeto_social',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='registro_mercantil',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='rfc_sociedad',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='testimonio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='tipo_sociedad',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
