# Generated by Django 3.2.9 on 2024-03-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0006_auto_20240312_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='beneficiiario1',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='beneficiiario2',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='beneficiiario3',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='parentesco1',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='parentesco2',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='parentesco3',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='porcentaje1',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='porcentaje2',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='porcentaje3',
        ),
    ]
