# Generated by Django 3.2.9 on 2024-03-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0007_auto_20240312_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='partes',
            name='beneficiiario1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partes',
            name='beneficiiario2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partes',
            name='beneficiiario3',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partes',
            name='parentesco1',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partes',
            name='parentesco2',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partes',
            name='parentesco3',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partes',
            name='porcentaje1',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='partes',
            name='porcentaje2',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='partes',
            name='porcentaje3',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
