# Generated by Django 3.2.9 on 2024-03-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0009_auto_20240312_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='partes',
            name='beneficiario1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partes',
            name='beneficiario2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partes',
            name='beneficiario3',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partes',
            name='parentesco1',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partes',
            name='parentesco2',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partes',
            name='parentesco3',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partes',
            name='porcentaje1',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='partes',
            name='porcentaje2',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='partes',
            name='porcentaje3',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
