# Generated by Django 3.2.9 on 2025-09-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cto', '0010_auto_20240312_1204'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tipocontrato',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', True), ('marcatipoContrato', True)), fields=('marcatipoContrato',), name='uniq_tipocontrato_true_only_one_active'),
        ),
    ]
